name: my_movies
description: "Movies list app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  package_info_plus: ^8.1.1
  http: ^1.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  lottie: ^3.1.3
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/inter/Inter-Thin.otf
        weight: 100
      - asset: assets/fonts/inter/Inter-ExtraLight.otf
        weight: 200
      - asset: assets/fonts/inter/Inter-Light.otf
        weight: 300
      - asset: assets/fonts/inter/Inter-Regular.otf
        weight: 400
      - asset: assets/fonts/inter/Inter-Medium.otf
        weight: 500
      - asset: assets/fonts/inter/Inter-SemiBold.otf
        weight: 600
      - asset: assets/fonts/inter/Inter-Bold.otf
        weight: 700
      - asset: assets/fonts/inter/Inter-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/inter/Inter-Black.otf
        weight: 900
  - family: Scripto
    fonts:
      - asset: assets/fonts/scripto/Scripto.otf
